import type { NextPage } from 'next';
import Head from 'next/head';
import { Container } from '@mui/material';

const Unauthorized: NextPage = () => {
  return (
    <Container maxWidth="md">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <pre>Unauthorized</pre>
    </Container>
  )
}

export default Unauthorized;
