import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Typography } from '@mui/material';
import { useUser } from '@astral-dx/core';
import { withPageAuthRequired } from '@astral-dx/core';
import { useBrand } from '@astral-dx/core';
import { Button } from '@astral-dx/core';
import { useReferences } from '@astral-dx/core';
import { useTeams } from '@astral-dx/core';
import { useCredentials } from '@astral-dx/core';

const Dashboard: NextPage = () => {
  const { user } = useUser();
  const { brand } = useBrand();
  const { references } = useReferences();
  const { teams } = useTeams();
  const { credentials } = useCredentials();

  return (
    <Container maxWidth="md">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <pre>{JSON.stringify(user, null, 2)}</pre>
      <img style={{ width: '100px' }} src={brand.logoSrc} />
      <Button>Hello World</Button>
      <Typography>{brand.title}</Typography>
      <Typography>{brand.subtitle}</Typography>
      { references.map((ref) => (
        <a href={ref.url} key={ref.url} target="_blank">
          <span className="material-symbols-rounded">
            {ref.icon}
          </span>
          {ref.label}
        </a>
      )) }
      <pre>{JSON.stringify(teams, null, 2)}</pre>
      <pre>{JSON.stringify(credentials, null, 2)}</pre>
    </Container>
  )
}

export const getServerSideProps = withPageAuthRequired({ redirectTo: '/unauthorized', permissions: [] });

export default Dashboard
